# fly.toml app configuration file generated for stellar-contract-bindings on 2025-03-02T10:29:57+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stellar-contract-bindings'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
